name: Lint and Publish latest
on:
  push:
    branches:
      - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v1

      - name: Install golangci-lint
        run: curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.24.0

      - name: Run golangci-lint
        run: $(go env GOPATH)/bin/golangci-lint run -c .golangci.yml --timeout=5m

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: Check out code
        uses: actions/checkout@v1

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build container image
        run: docker build -t kelonio/oathkeeper:$(git rev-parse --short HEAD) -t kelonio/oathkeeper:stable .

      - name: Push images to DockerHub
        run: echo kelonio/oathkeeper:$(git rev-parse --short HEAD) kelonio/oathkeeper:stable | xargs -n 1 docker push